In [2]:
import numpy as np

data = np.array([[22.5,19.0,31.2,28.7,25.1],
                 [17.3,22.8,30.5,26.4,21.9],
                 [33.1,29.6,18.4,24.0,27.8],
                 [20.2,23.5,31.9,28.1,22.6]])

print(data)

[[22.5 19.  31.2 28.7 25.1]
 [17.3 22.8 30.5 26.4 21.9]
 [33.1 29.6 18.4 24.  27.8]
 [20.2 23.5 31.9 28.1 22.6]]


# Task 1 – Print Shape and Mean per Station

In [3]:
# Print shape
print("Shape of data:", data.shape)

# Mean temperature per station
mean_temp = np.mean(data, axis=1)

print("Mean temperature per station:", mean_temp)

Shape of data: (4, 5)
Mean temperature per station: [25.3  23.78 26.58 25.26]


Explanation (simple):

(4,5) → 4 stations and 5 readings each

axis=1 → calculate mean for each row (station)

# Task 2 – Extract Temperatures Above 28°C

In [4]:
# Boolean mask for temperatures above 28
high_temp = data[data > 28]

print("Temperatures above 28°C:", high_temp)

Temperatures above 28°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


Explanation:

data > 28 finds values greater than 28

It returns them as a 1D array

# Task 3 – Normalize Data 

In [5]:


normalized = (data - data.min()) / (data.max() - data.min())

# round to 2 decimal places
normalized = np.round(normalized, 2)

print("Normalized Data:\n", normalized)

Normalized Data:
 [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]


Explanation:

min value = 17.3

max value = 33.1

Converts all values between 0 and 1

# Final Notebook Structure

## Cell 1

In [6]:
import numpy as np
data = np.array([...])

# Cell 2

In [8]:
# task 1 code + output

# Cell 3

In [9]:
# task 2 code + output


# Cell 4


In [10]:
# task 3 code + output